### PR TITLE
Fix ethernet speed

### LINKED ISSUE #6: Ethernet is slower compared to Wi-Fi
### Issue

Hello,

I received my AI-On-The-Edge Cam :-)
It works well over Ethernet, PoE, and Wi-Fi.

Over PoE, the module consumes so little power that my switch (GS308EPP) restarts it several times before it works.

Otherwise, I find the network speed is faster over Wi-Fi than over Ethernet. Have you noticed the same thing?

While searching online, I found this: https://esp32.com/viewtopic.php?t=39779
Could this be related?

### PR DESCRIPTION
**Pull request by ge0rdi**
ISR handler service was not installed. So `esp_eth_mac_new_w5500` was unable to register its interrupt handler and thus networking stack was not notified about incoming packets.

Fixes #6

### CODE REVIEW

File: code/components/allexok_lan/connect_lan.cpp [hunk 1]
```diff
@@ -137,9 +137,6 @@ int lan_init(void)
     gpio_set_direction(ETH_ENABLE, GPIO_MODE_OUTPUT);
     gpio_set_level(ETH_ENABLE, 1);
 
-    gpio_set_direction(ETH_INT, GPIO_MODE_INPUT);
```
Comment (ge0rdi) [inline code/components/allexok_lan/connect_lan.cpp:140]: This is not needed because `esp_eth_mac_new_w5500` will properly configure interrupt PIN.

File: code/components/allexok_lan/connect_lan.cpp [hunk 2]
```diff
@@ -167,6 +166,7 @@ int lan_init(void)
 
     eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();
     phy_config.phy_addr = 1; // typical W5500
+    phy_config.reset_gpio_num = -1;
```
Comment (ge0rdi) [inline code/components/allexok_lan/connect_lan.cpp:169]: Since we don't use _reset_, we should set this to -1.
Otherwise default pin 5 will be used.
It probably doesn't matter. But if such reset is done by network stack at some random time, it may interfere with what is connected to pin 5.
